import { useQuery } from "@tanstack/react-query";
import { apiRequest } from "../lib/api";

const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const statusLabels: Record<string, string> = { RASCUNHO: "Rascunho", PENDENTE_VALIDACAO: "Pendente de validação", AGUARDANDO_RECEBIMENTO: "Aguardando recebimento", AGUARDANDO_APROVACAO: "Aguardando autorização", APROVADA_PAGAMENTO: "Autorizada", AGENDADA: "Agendada", PAGA_PARCIALMENTE: "Paga parcialmente", PAGA: "Paga", VENCIDA: "Vencida", CONTESTADA: "Contestada", CANCELADA: "Cancelada" };

export function FinancePage() {
  const dashboard = useQuery({ queryKey: ["financial-dashboard"], queryFn: () => apiRequest<any>("/financial/dashboard") });
  const payables = useQuery({ queryKey: ["accounts-payable"], queryFn: () => apiRequest<any>("/accounts-payable") });
  return <div className="space-y-6">
    <header><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-700">Financeiro</p><h1 className="text-3xl font-extrabold">Contas a pagar</h1><p className="mt-1 text-slate-600">Títulos rastreados até a nota, o recebimento e a autorização do pagamento.</p></header>
    {dashboard.isError ? <p className="rounded-xl border border-red-200 bg-red-50 p-3 text-red-800">{(dashboard.error as Error).message}</p> : null}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Em aberto", dashboard.data?.openAmount], ["Vencido", dashboard.data?.overdueAmount], ["Pago no período", dashboard.data?.paidAmount], ["Aguardando autorização", dashboard.data?.awaitingApproval]].map(([label, value], index) => <article className="card" key={String(label)}><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-extrabold">{index === 3 ? Number(value ?? 0) : brl.format(Number(value ?? 0))}</p></article>)}</section>
    <section className="card"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="section-title">Títulos recentes</h2><span className="text-sm text-slate-500">Valores visíveis somente com permissão financeira</span></div>{payables.isLoading ? <p className="py-8 text-center text-slate-500">Carregando…</p> : null}{payables.isError ? <p className="text-red-700">{(payables.error as Error).message}</p> : null}<div className="mt-4 grid gap-3">{payables.data?.map((item: any) => <article className="rounded-2xl border p-4" key={item.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-extrabold">{item.supplier?.name}</h3><p className="text-sm text-slate-500">Documento {item.documentNumber} · {item.category?.name}</p></div><span className="badge bg-slate-100 text-slate-800">{statusLabels[item.status] ?? item.status}</span></div><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-slate-500">Valor líquido</dt><dd className="font-bold">{brl.format(Number(item.netAmount))}</dd></div><div><dt className="text-slate-500">Parcelas</dt><dd className="font-semibold">{item.installments?.length ?? 0}</dd></div><div><dt className="text-slate-500">Origem</dt><dd className="font-semibold">{item.fiscalDocument ? `Nota ${item.fiscalDocument.number}` : item.origin}</dd></div><div><dt className="text-slate-500">OC</dt><dd className="font-semibold">{item.purchaseOrder ? `OC-${String(item.purchaseOrder.number).padStart(6, "0")}` : "Sem OC"}</dd></div></dl></article>)}</div></section>
  </div>;
}
