import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "../lib/api";

export function FiscalDocumentsPage() {
  const queryClient = useQueryClient(); const [file, setFile] = useState<File | null>(null); const [reason, setReason] = useState("");
  const list = useQuery({ queryKey: ["fiscal-documents"], queryFn: () => apiRequest<any[]>("/fiscal-documents") });
  const upload = useMutation({ mutationFn: async () => { if (!file) throw new Error("Selecione um XML ou ZIP."); const data = new FormData(); data.set("idempotencyKey", crypto.randomUUID()); if (reason) data.set("withoutOrderReason", reason); data.set("file", file); return apiRequest("/fiscal-documents/nfe/import", { method: "POST", body: data }); }, onSuccess: () => { setFile(null); setReason(""); void queryClient.invalidateQueries({ queryKey: ["fiscal-documents"] }); } });
  return <div className="space-y-6"><header><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-700">Financeiro</p><h1 className="text-3xl font-extrabold">Entrada de notas</h1><p className="mt-1 text-slate-600">Importação idempotente, validação fiscal e vínculo por item com a Ordem de Compra.</p></header><form className="card space-y-4" onSubmit={(event) => { event.preventDefault(); upload.mutate(); }}><h2 className="section-title">Importar NF-e</h2><label className="block text-sm font-semibold">XML ou ZIP<input className="input mt-1" type="file" accept=".xml,.zip,application/xml,application/zip" required onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label><label className="block text-sm font-semibold">Justificativa quando não houver OC<textarea className="input mt-1 min-h-20" value={reason} onChange={(event) => setReason(event.target.value)} /></label><button className="btn-primary min-h-12" disabled={upload.isPending}>{upload.isPending ? "Importando…" : "Importar documento"}</button>{upload.isError ? <p className="text-red-700">{(upload.error as Error).message}</p> : null}</form><section className="card"><h2 className="section-title">Documentos recebidos</h2><div className="mt-4 grid gap-3">{list.data?.map((item) => <article className="rounded-2xl border p-4" key={item.id}><div className="flex flex-wrap justify-between gap-2"><div><h3 className="font-extrabold">{item.type} {item.number}{item.series ? `/${item.series}` : ""}</h3><p className="text-sm text-slate-500">{item.supplier?.name} · {Number(item.netAmount).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</p></div><span className="badge bg-slate-100 text-slate-800">{item.status}</span></div></article>)}</div></section></div>;
}
