import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useLocation } from "react-router-dom";
import { apiRequest } from "../lib/api";
import { useAuth, userHasPermission } from "../lib/auth";

type Balance = { physical: string; reserved: string; available: string; curing: string; blocked: string; losses: string };
type Product = { id: string; code: string; name?: string | null; description: string; category?: string | null; unit: string; unitPrice: string; stockMinimum: string; isActive: boolean; costPending: boolean; isManufactured: boolean; industrialConfig?: { currentUnitCost?: string; cureRequired: boolean; cureDuration?: number | null; cureTimeUnit: "HORAS" | "DIAS" } | null; balance: Balance };
type Movement = { id: string; movementType: string; quantity: string; totalCost?: string; occurredAt: string; origin?: string | null; product: { code: string; name?: string | null; description: string; unit: string }; lot?: { code: string } | null };
type Overview = { products: Product[]; indicators: Record<string, string | number | undefined>; recentMovements: Movement[] };
type Options = { products: Array<Omit<Product, "balance">>; sectors: Array<{ id: string; code: string; name: string }>; reasons: Array<{ id: string; code: string; name: string; allowedTypes: string[] }>; employees: Array<{ id: string; name: string }>; permissions: { viewCost: boolean } };

const tabs = [["/estoque", "Visão geral"], ["/estoque/produtos", "Produtos"], ["/estoque/lancamentos", "Produtos, perdas e qualidade"], ["/estoque/lotes", "Lotes em cura"], ["/estoque/movimentacoes", "Movimentações"], ["/estoque/inventario", "Inventário"], ["/estoque/cadastros", "Cadastros auxiliares"]] as const;
const money = (v: unknown) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(v ?? 0));
const qty = (v: unknown) => Number(v ?? 0).toLocaleString("pt-BR", { maximumFractionDigits: 4 });
const date = (v?: string | null) => v ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(v)) : "—";
const label = (v: string) => v.replaceAll("_", " ").toLowerCase().replace(/^./, (x) => x.toUpperCase());

export function InventoryPage({ operationalSection }: { operationalSection?: "lancamentos" | "inventario" } = {}) {
  const { pathname } = useLocation(); const { user } = useAuth(); const client = useQueryClient();
  const can = (permission: string) => userHasPermission(user, permission) || (operationalSection === "inventario" && permission === "INVENTORY_COUNT");
  const tab = operationalSection ?? (pathname === "/estoque" ? "overview" : pathname.split("/").slice(-1)[0]);
  const [search, setSearch] = useState(""); const [editing, setEditing] = useState<Product | null>(null); const [notice, setNotice] = useState("");
  const [entry, setEntry] = useState({ productId: "", entryType: "PRODUTO_ACABADO", quantity: "", sectorId: "", reasonId: "", responsibleId: "", lossOrigin: "", sourceFromProduction: false, notes: "" });
  const overview = useQuery({ queryKey: ["inventory-overview", operationalSection], queryFn: () => apiRequest<Overview>(operationalSection === "inventario" ? "/operation/inventory/products" : "/inventory/overview?situation=TODOS"), enabled: operationalSection !== "lancamentos", refetchInterval: 30000 });
  const options = useQuery({ queryKey: ["inventory-options", operationalSection], queryFn: () => apiRequest<Options>(operationalSection ? "/operation/inventory/options" : "/inventory/options") });
  const movements = useQuery({ queryKey: ["inventory-movements"], queryFn: () => apiRequest<{ items: Movement[] }>("/inventory/movements?pageSize=100"), enabled: tab === "movimentacoes" });
  const industrial = useQuery({ queryKey: ["industrial-summary-inventory"], queryFn: () => apiRequest<any>("/industrial/summary"), enabled: tab === "lotes" });
  const counts = useQuery({ queryKey: ["inventory-counts"], queryFn: () => apiRequest<any[]>("/inventory/counts"), enabled: tab === "inventario" });
  const products = useMemo(() => (overview.data?.products ?? []).filter((p) => `${p.code} ${p.name ?? p.description}`.toLowerCase().includes(search.toLowerCase())), [overview.data, search]);
  const refresh = () => { void client.invalidateQueries({ queryKey: ["inventory-overview"] }); void client.invalidateQueries({ queryKey: ["inventory-options"] }); };
  const postEntry = useMutation({ mutationFn: () => apiRequest("/inventory/entries", { method: "POST", body: JSON.stringify({ ...entry, lossOrigin: entry.lossOrigin || undefined }) }), onSuccess: () => { setNotice("Lançamento registrado com custo histórico e rastreabilidade."); setEntry({ ...entry, quantity: "", notes: "" }); refresh(); }, onError: (e) => setNotice(e instanceof Error ? e.message : "Falha no lançamento") });
  const startCount = useMutation({ mutationFn: () => apiRequest("/inventory/counts", { method: "POST", body: JSON.stringify({ productIds: products.filter((p) => p.isActive).map((p) => p.id), notes: "Inventário geral" }) }), onSuccess: () => { setNotice("Inventário iniciado com snapshot do saldo esperado."); void counts.refetch(); }, onError: (e) => setNotice(e instanceof Error ? e.message : "Falha ao iniciar inventário") });
  const saveProduct = useMutation({ mutationFn: (form: FormData) => { if (!editing) throw new Error("Produto não selecionado"); return apiRequest(`/commercial/products/${editing.id}`, { method: "PUT", body: JSON.stringify({ code: form.get("code"), name: form.get("name"), description: form.get("description"), category: form.get("category") || null, unit: form.get("unit"), unitCost: form.get("unitCost"), suggestedPrice: form.get("suggestedPrice"), isManufactured: form.get("isManufactured") === "on", cureRequired: form.get("cureRequired") === "on", cureDuration: form.get("cureDuration") ? Number(form.get("cureDuration")) : null, cureTimeUnit: form.get("cureTimeUnit"), stockMinimum: form.get("stockMinimum"), technicalNotes: form.get("technicalNotes") || null, isActive: form.get("isActive") === "on", costChangeReason: form.get("costChangeReason") || null }) }); }, onSuccess: () => { setEditing(null); setNotice("Produto atualizado sem recalcular o histórico."); refresh(); }, onError: (e) => setNotice(e instanceof Error ? e.message : "Falha ao atualizar") });
  if ((operationalSection !== "lancamentos" && overview.isLoading) || options.isLoading) return <div className="card">Carregando estoque real...</div>;
  if ((operationalSection !== "lancamentos" && !overview.data) || !options.data) return <div className="card text-red-700">Não foi possível carregar o estoque.</div>;
  const i = overview.data?.indicators ?? {};
  const cards = [["Produtos ativos", i.activeProducts], ["Com saldo disponível", i.withAvailable], ["Saldo zerado", i.zeroAvailable], ["Abaixo do mínimo", i.belowMinimum], ["Quantidade em cura", qty(i.curingQuantity)], ["Bloqueado por qualidade", qty(i.blockedQuantity)], ["Perdas no período", qty(i.lossQuantity)], ["Custo das perdas", options.data.permissions.viewCost ? money(i.lossCost) : "Restrito"], ["Testes de engenharia", i.engineeringTests]];
  return <div className="space-y-5">
    <header className="card bg-slate-950 text-white"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Arcovan · Operação</p><h2 className="mt-2 text-3xl font-extrabold">{operationalSection === "lancamentos" ? "Produtos, perdas e qualidade" : operationalSection === "inventario" ? "Inventário" : "Estoque de produtos acabados"}</h2><p className="mt-2 text-sm text-slate-300">Lançamentos integrados à mesma base administrativa, sem duplicação de registros.</p></header>
    {!operationalSection ? <nav className="flex gap-2 overflow-x-auto pb-1">{tabs.map(([to, text]) => <Link key={to} to={to} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm font-bold ${pathname === to ? "bg-brand-700 text-white" : "bg-white text-slate-700 shadow"}`}>{text}</Link>)}</nav> : null}
    {notice ? <div className="rounded-xl border border-brand-200 bg-brand-50 p-3 text-sm font-bold text-brand-900">{notice}</div> : null}
    {tab === "overview" ? <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([name, value]) => <Link to="/estoque/produtos" className="card hover:shadow-lg" key={String(name)}><p className="text-sm text-slate-500">{name}</p><p className="mt-2 text-3xl font-extrabold text-brand-700">{value}</p></Link>)}</div><section className="card"><h3 className="section-title mb-4">Movimentações recentes</h3><MovementTable items={overview.data?.recentMovements ?? []} viewCost={options.data.permissions.viewCost} /></section></> : null}
    {tab === "produtos" ? <section className="card overflow-x-auto"><div className="mb-4 flex flex-wrap justify-between gap-3"><div><h3 className="section-title">Todos os produtos controlados</h3><p className="text-sm text-slate-500">Ativos aparecem mesmo com saldo zero; o saldo não é editável.</p></div><input className="input max-w-xs" placeholder="Código ou produto" value={search} onChange={(e) => setSearch(e.target.value)} /></div><table className="w-full min-w-[1100px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500">{["Código", "Produto", "Un.", "Físico", "Reservado", "Disponível", "Em cura", "Bloqueado", "Custo", "Situação", ""].map((x) => <th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{products.map((p) => <tr className="border-b" key={p.id}><td className="p-3 font-bold">{p.code}</td><td>{p.name ?? p.description}</td><td>{p.unit}</td><td>{qty(p.balance.physical)}</td><td>{qty(p.balance.reserved)}</td><td className="font-bold">{qty(p.balance.available)}</td><td>{qty(p.balance.curing)}</td><td>{qty(p.balance.blocked)}</td><td>{options.data.permissions.viewCost ? p.costPending ? <span className="badge bg-amber-50 text-amber-800">Custo pendente</span> : money(p.industrialConfig?.currentUnitCost) : "Restrito"}</td><td>{p.isActive ? "Ativo" : "Inativo"}</td><td>{can("PRODUCT_MANAGE") ? <button className="btn-secondary" onClick={() => setEditing(p)}>Editar</button> : null}</td></tr>)}</tbody></table></section> : null}
    {tab === "lancamentos" ? <section className="card"><h3 className="section-title">Novo lançamento</h3><p className="mb-5 text-sm text-slate-500">Custo capturado do produto e total calculado no backend.</p><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Field text="Tipo"><select className="select" value={entry.entryType} onChange={(e) => setEntry({ ...entry, entryType: e.target.value, reasonId: "" })}><option value="PRODUTO_ACABADO">Produto acabado</option><option value="PERDA_PRODUTO">Perda de produto</option><option value="BAIXA_QUALIDADE">Baixa qualidade</option><option value="TESTE_ENGENHARIA">Teste de engenharia</option></select></Field><Field text="Produto"><select className="select" value={entry.productId} onChange={(e) => setEntry({ ...entry, productId: e.target.value })}><option value="">Selecione</option>{options.data.products.map((p) => <option value={p.id} key={p.id}>{p.code} · {p.name ?? p.description}</option>)}</select></Field><Field text="Quantidade"><input className="input" type="number" step="0.0001" min="0.0001" value={entry.quantity} onChange={(e) => setEntry({ ...entry, quantity: e.target.value })} /></Field><Field text="Setor"><select className="select" value={entry.sectorId} onChange={(e) => setEntry({ ...entry, sectorId: e.target.value })}><option value="">Selecione</option>{options.data.sectors.map((x) => <option value={x.id} key={x.id}>{x.name}</option>)}</select></Field><Field text="Motivo"><select className="select" value={entry.reasonId} onChange={(e) => setEntry({ ...entry, reasonId: e.target.value })}><option value="">Selecione</option>{options.data.reasons.filter((r) => !r.allowedTypes.length || r.allowedTypes.includes(entry.entryType)).map((r) => <option value={r.id} key={r.id}>{r.code} · {r.name}</option>)}</select></Field><Field text="Responsável"><select className="select" value={entry.responsibleId} onChange={(e) => setEntry({ ...entry, responsibleId: e.target.value })}><option value="">Selecione</option>{options.data.employees.map((x) => <option value={x.id} key={x.id}>{x.name}</option>)}</select></Field>{entry.entryType === "PERDA_PRODUTO" ? <Field text="Origem da perda"><select className="select" value={entry.lossOrigin} onChange={(e) => setEntry({ ...entry, lossOrigin: e.target.value })}><option value="">Selecione</option>{["FABRICACAO", "CURA", "ESTOQUE_DISPONIVEL", "SEPARACAO", "CARREGAMENTO", "TRANSPORTE", "DESCARREGAMENTO", "OUTRA"].map((x) => <option value={x} key={x}>{label(x)}</option>)}</select></Field> : null}<Field text="Observações / justificativa"><textarea className="input" value={entry.notes} onChange={(e) => setEntry({ ...entry, notes: e.target.value })} /></Field></div><button className="btn-primary mt-5" disabled={postEntry.isPending} onClick={() => postEntry.mutate()}>Registrar lançamento</button></section> : null}
    {tab === "lotes" ? <section className="card overflow-x-auto"><h3 className="section-title mb-4">Lotes em cura e inspeção</h3><table className="w-full min-w-[800px] text-sm"><thead><tr className="border-b text-left"><th className="p-3">Lote</th><th>Produto</th><th>Quantidade</th><th>Produção</th><th>Previsão</th><th>Status</th></tr></thead><tbody>{(industrial.data?.lots ?? []).map((lot: any) => <tr className="border-b" key={lot.id}><td className="p-3 font-bold">{lot.code}</td><td>{lot.product.code} · {lot.product.description}</td><td>{qty(lot.quantity)}</td><td>{date(lot.manufacturedAt)}</td><td>{date(lot.cureReleaseAt)}</td><td><span className="badge">{label(lot.status)}</span></td></tr>)}</tbody></table></section> : null}
    {tab === "movimentacoes" ? <section className="card"><h3 className="section-title mb-4">Histórico imutável de movimentações</h3><MovementTable items={movements.data?.items ?? []} viewCost={options.data.permissions.viewCost} /></section> : null}
    {tab === "inventario" ? <section className="space-y-4"><div className="card flex flex-wrap justify-between gap-3"><div><h3 className="section-title">Inventário físico</h3><p className="text-sm text-slate-500">Divergências geram ajuste somente após aprovação.</p></div>{can("INVENTORY_COUNT") ? <button className="btn-primary" onClick={() => startCount.mutate()}>Iniciar inventário geral</button> : null}</div>{(counts.data ?? []).map((count: any) => <article className="card" key={count.id}><div className="flex justify-between"><strong>{count.code}</strong><span className="badge">{label(count.status)}</span></div><p className="mt-2 text-sm text-slate-500">{count.items.length} produtos · {date(count.createdAt)}</p></article>)}</section> : null}
    {tab === "cadastros" ? <section className="grid gap-4 lg:grid-cols-2"><div className="card"><h3 className="section-title mb-3">Setores</h3>{options.data.sectors.map((x) => <div className="border-b p-3" key={x.id}><strong>{x.code}</strong> · {x.name}</div>)}</div><div className="card"><h3 className="section-title mb-3">Motivos configuráveis</h3>{options.data.reasons.map((x) => <div className="border-b p-3 text-sm" key={x.id}><strong>{x.code}</strong> · {x.name}</div>)}</div></section> : null}
    {editing ? <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-4"><form className="mx-auto grid max-w-3xl gap-4 rounded-2xl bg-white p-6 md:grid-cols-2" onSubmit={(e) => { e.preventDefault(); saveProduct.mutate(new FormData(e.currentTarget)); }}><h3 className="section-title md:col-span-2">Editar produto</h3>{[["code", "Código", editing.code], ["name", "Nome", editing.name ?? editing.description], ["description", "Descrição", editing.description], ["category", "Família", editing.category ?? ""], ["unit", "Unidade", editing.unit], ["unitCost", "Custo unitário", editing.industrialConfig?.currentUnitCost ?? "0"], ["suggestedPrice", "Preço sugerido", editing.unitPrice], ["stockMinimum", "Estoque mínimo", editing.stockMinimum], ["cureDuration", "Prazo de cura", editing.industrialConfig?.cureDuration ?? ""], ["costChangeReason", "Justificativa de custo", ""], ["technicalNotes", "Observações técnicas", ""]].map(([name, text, value]) => <Field text={String(text)} key={String(name)}><input className="input" name={String(name)} defaultValue={String(value)} /></Field>)}<Field text="Unidade do prazo"><select className="select" name="cureTimeUnit" defaultValue={editing.industrialConfig?.cureTimeUnit ?? "HORAS"}><option value="HORAS">Horas</option><option value="DIAS">Dias</option></select></Field><div className="flex gap-4 md:col-span-2"><label><input type="checkbox" name="isManufactured" defaultChecked={editing.isManufactured} /> Fabricado</label><label><input type="checkbox" name="cureRequired" defaultChecked={editing.industrialConfig?.cureRequired} /> Exige cura</label><label><input type="checkbox" name="isActive" defaultChecked={editing.isActive} /> Ativo</label></div><div className="flex justify-end gap-2 md:col-span-2"><button type="button" className="btn-secondary" onClick={() => setEditing(null)}>Cancelar</button><button className="btn-primary">Salvar</button></div></form></div> : null}
  </div>;
}
function Field({ text, children }: { text: string; children: React.ReactNode }) { return <label className="block text-sm font-bold text-slate-700">{text}<div className="mt-1">{children}</div></label>; }
function MovementTable({ items, viewCost }: { items: Movement[]; viewCost: boolean }) { return items.length ? <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead><tr className="border-b text-left"><th className="p-3">Data</th><th>Produto</th><th>Tipo</th><th>Quantidade</th><th>Lote</th><th>Custo</th><th>Origem</th></tr></thead><tbody>{items.map((x) => <tr className="border-b" key={x.id}><td className="p-3">{date(x.occurredAt)}</td><td>{x.product.code} · {x.product.name ?? x.product.description}</td><td><span className="badge">{label(x.movementType)}</span></td><td>{qty(x.quantity)} {x.product.unit}</td><td>{x.lot?.code ?? "—"}</td><td>{viewCost ? money(x.totalCost) : "Restrito"}</td><td>{x.origin ?? "—"}</td></tr>)}</tbody></table></div> : <div className="rounded-xl border border-dashed p-8 text-center text-slate-500">Nenhuma movimentação registrada.</div>; }
