import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiRequest, getApiUrl } from "../lib/api";

type Section = "quotes" | "approvals" | "orders" | "receipts";
const labels = { quotes: ["Cotações", "Solicitações disponíveis para composição do mapa de cotações"], approvals: ["Aprovações de compra", "Decisão segregada da autorização de pagamento"], orders: ["Ordens de Compra", "Documentos emitidos e versões imutáveis"], receipts: ["Recebimentos", "Entradas físicas, parciais e divergências"] } as const;

export function ProcurementWorkflowPage({ section }: { section: Section }) {
  const queryClient = useQueryClient(); const endpoint = section === "approvals" ? "/purchase-approvals/pending" : section === "orders" ? "/purchase-orders" : section === "receipts" ? "/goods-receipts" : "/purchase-requests";
  const list = useQuery({ queryKey: ["procurement-workspace", section], queryFn: () => apiRequest<any>(endpoint) });
  const items = Array.isArray(list.data) ? list.data : list.data?.items ?? [];
  const decide = useMutation({ mutationFn: ({ id, decision }: { id: string; decision: string }) => apiRequest(`/purchase-requests/${id}/approve`, { method: "POST", body: JSON.stringify({ decision, reason: decision === "APROVADA" ? undefined : "Devolução registrada pelo painel de aprovação." }) }), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ["procurement-workspace", section] }) });
  async function openPdf(id: string) { const token = localStorage.getItem("smartcheck.token"); const response = await fetch(getApiUrl(`/purchase-orders/${id}/pdf`), { headers: token ? { Authorization: `Bearer ${token}` } : {} }); if (!response.ok) throw new Error("Não foi possível gerar a Ordem de Compra."); const url = URL.createObjectURL(await response.blob()); window.open(url, "_blank", "noopener,noreferrer"); setTimeout(() => URL.revokeObjectURL(url), 60_000); }
  return <div className="space-y-6"><header><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-700">Compras</p><h1 className="text-3xl font-extrabold">{labels[section][0]}</h1><p className="mt-1 text-slate-600">{labels[section][1]}</p></header><section className="card">{list.isLoading ? <p className="py-8 text-center text-slate-500">Carregando…</p> : null}{list.isError ? <p className="text-red-700">{(list.error as Error).message}</p> : null}<div className="grid gap-3">{items.map((item: any) => {
    const request = item.purchaseRequest ?? item; const order = item.purchaseOrder ?? item; return <article className="rounded-2xl border p-4" key={item.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-extrabold">{section === "orders" ? `OC-${String(item.number).padStart(6, "0")}` : section === "receipts" ? `Recebimento ${item.number} · OC-${String(order.number ?? "").padStart(6, "0")}` : request.displayNumber}</h2><p className="text-sm text-slate-500">{request.purpose ?? item.supplier?.name ?? order.supplier?.name}</p></div><span className="badge bg-slate-100 text-slate-800">{item.status ?? request.status}</span></div>{section === "approvals" ? <div className="mt-3 flex flex-wrap gap-2"><button className="btn-primary" disabled={decide.isPending} onClick={() => decide.mutate({ id: request.id, decision: "APROVADA" })}>Aprovar compra</button><button className="btn-secondary" disabled={decide.isPending} onClick={() => decide.mutate({ id: request.id, decision: "DEVOLVIDA_COTACAO" })}>Devolver para cotação</button></div> : null}{section === "orders" ? <button className="btn-secondary mt-3" onClick={() => void openPdf(item.id)}>Abrir PDF oficial</button> : null}{section === "receipts" && item.divergences?.length ? <p className="mt-3 rounded-xl bg-amber-50 p-2 text-sm font-semibold text-amber-900">{item.divergences.length} divergência(s) registrada(s).</p> : null}</article>;
  })}{!list.isLoading && !items.length ? <p className="py-8 text-center text-slate-500">Nenhum registro nesta etapa.</p> : null}</div>{decide.isError ? <p className="mt-3 text-red-700">{(decide.error as Error).message}</p> : null}</section></div>;
}
