import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiRequest, getApiUrl } from "../lib/api";
import { useAuth, userHasPermission } from "../lib/auth";

type QuoteStatus = "RASCUNHO" | "EMITIDO" | "ENVIADO" | "APROVADO" | "REJEITADO" | "VENCIDO" | "CONVERTIDO" | "CANCELADO";
type Product = { id: string; code: string; name?: string | null; description: string; category?: string | null; unit: string; unitPrice: string; stockMinimum?: string; isActive: boolean; industrialConfig?: { currentUnitCost?: string; cureRequired: boolean; cureDuration?: number | null; cureTimeUnit: "HORAS" | "DIAS" } | null };
type QuoteItem = { catalogItemId: string; quantity: string; unitPrice: string; code?: string; description?: string; unit?: string; total?: string; unitCostSnapshot?: string; costTotal?: string; marginValue?: string; marginPercent?: string };
type Quote = { id: string; number: string; issueDate: string; validityDate: string; status: QuoteStatus; total: string; grossTotal?: string; productCostTotal?: string; commissionAmount?: string; internalTaxAmount?: string; marginValue?: string; marginPercent?: string; customerId?: string | null; customerNameSnapshot?: string | null; customerPhoneSnapshot?: string | null; deliveryLocation?: string | null; paymentTermId?: string | null; salespersonId?: string | null; paymentTerms?: string | null; hasCommission?: boolean; salesSystem?: "SHVENDAS" | "WEBMAIS"; commercialNotes?: string | null; customer?: { legalName: string; phone?: string | null; addressLine?: string | null } | null; salesperson?: { code: string; name: string } | null; items?: QuoteItem[] };
type Options = { company: { legalName: string }; defaultDates: { issueDate: string; validityDate: string }; customers: Array<{ id: string; legalName: string; phone?: string | null; addressLine?: string | null; deliveryAddresses: Array<{ address: string }> }>; paymentTerms: Array<{ id: string; name: string }>; salespersons: Array<{ id: string; code: string; name: string }>; catalogItems: Product[]; financialConfig?: { commissionRate: string; webmaisTaxRate: string; shvTaxRate: string } | null; permissions: { viewCost: boolean; viewMargin: boolean; editPrice: boolean } };
type ListResponse = { items: Quote[]; total: number; page: number; pageSize: number; summary: { total: number; open: number; approved: number; rejected: number; expired: number; quotedValue: string } };

type Form = { customerId: string; customerName: string; customerPhone: string; deliveryLocation: string; paymentTermId: string; salespersonId: string; hasCommission: "" | "true" | "false"; salesSystem: "" | "SHVENDAS" | "WEBMAIS"; commercialNotes: string; items: QuoteItem[] };
const blankItem = (): QuoteItem => ({ catalogItemId: "", quantity: "1", unitPrice: "" });
const blankForm = (): Form => ({ customerId: "", customerName: "", customerPhone: "", deliveryLocation: "", paymentTermId: "", salespersonId: "", hasCommission: "", salesSystem: "", commercialNotes: "", items: [blankItem()] });
const brl = (value?: string | number | null) => value === undefined || value === null ? "—" : new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value));
const brDate = (value?: string) => value ? new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(value)) : "—";
const statusLabel: Record<QuoteStatus, string> = { RASCUNHO: "Rascunho", EMITIDO: "Emitido", ENVIADO: "Enviado", APROVADO: "Aprovado", REJEITADO: "Rejeitado", VENCIDO: "Expirado", CONVERTIDO: "Convertido em pedido", CANCELADO: "Cancelado" };

async function openPdf(id: string, download = false) {
  const token = localStorage.getItem("smartcheck.token");
  const response = await fetch(getApiUrl(`/quotes/${id}/pdf?disposition=${download ? "attachment" : "inline"}`), { headers: token ? { Authorization: `Bearer ${token}` } : undefined });
  if (!response.ok) throw new Error((await response.json().catch(() => null))?.message ?? "Falha ao gerar o PDF");
  const url = URL.createObjectURL(await response.blob());
  if (download) { const anchor = document.createElement("a"); anchor.href = url; anchor.download = `orcamento-${id}.pdf`; anchor.click(); } else window.open(url, "_blank", "noopener,noreferrer");
  window.setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

export function QuotesPage() {
  const { user } = useAuth();
  const client = useQueryClient();
  const can = (permission: string) => userHasPermission(user, permission);
  const [tab, setTab] = useState<"quotes" | "products">("quotes");
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<Form>(blankForm());
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [message, setMessage] = useState("");
  const [filters, setFilters] = useState({ number: "", status: "", page: 1 });
  const [productSearch, setProductSearch] = useState("");
  const [showProductForm, setShowProductForm] = useState(false);
  const [productForm, setProductForm] = useState({ code: "", name: "", description: "", category: "", unit: "UN", unitCost: "", suggestedPrice: "", cureRequired: true, cureDuration: "", cureTimeUnit: "DIAS" as "HORAS" | "DIAS", stockMinimum: "0", technicalNotes: "" });

  const optionsQuery = useQuery({ queryKey: ["quote-options"], queryFn: () => apiRequest<Options>("/quotes/options") });
  const queryString = useMemo(() => { const params = new URLSearchParams({ page: String(filters.page), pageSize: "20" }); if (filters.number) params.set("number", filters.number); if (filters.status) params.set("status", filters.status); return params.toString(); }, [filters]);
  const quotesQuery = useQuery({ queryKey: ["quotes", queryString], queryFn: () => apiRequest<ListResponse>(`/quotes?${queryString}`) });
  const productsQuery = useQuery({ queryKey: ["commercial-products"], queryFn: () => apiRequest<Product[]>("/commercial/products"), enabled: tab === "products" });
  const options = optionsQuery.data;

  const preview = useMemo(() => {
    let gross = 0; let cost = 0; let missingCost = false;
    for (const item of form.items) { const product = options?.catalogItems.find((candidate) => candidate.id === item.catalogItemId); const quantity = Number(item.quantity) || 0; const price = Number(item.unitPrice) || 0; gross += quantity * price; if (product?.industrialConfig?.currentUnitCost === undefined) missingCost = true; else cost += quantity * Number(product.industrialConfig.currentUnitCost); }
    const commission = form.hasCommission === "true" ? gross * Number(options?.financialConfig?.commissionRate ?? 5) / 100 : 0;
    const taxes = form.salesSystem === "WEBMAIS" ? gross * Number(options?.financialConfig?.webmaisTaxRate ?? 18) / 100 : 0;
    const margin = gross - cost - commission - taxes;
    return { gross, cost, commission, taxes, margin, percent: gross ? margin / gross * 100 : 0, missingCost };
  }, [form, options]);

  function validate() {
    const next: Record<string, string> = {};
    if (!form.customerName.trim()) next.customerName = "Informe o nome do cliente.";
    if (form.customerPhone.replace(/\D/g, "").length < 10) next.customerPhone = "Informe um telefone válido com DDD.";
    if (!form.deliveryLocation.trim()) next.deliveryLocation = "Informe o local de entrega.";
    if (!form.paymentTermId) next.paymentTermId = "Selecione a condição de pagamento.";
    if (!form.salespersonId) next.salespersonId = "Selecione o responsável comercial.";
    if (!form.hasCommission) next.hasCommission = "Informe se existe comissão.";
    if (!form.salesSystem) next.salesSystem = "Selecione o sistema comercial.";
    if (!form.items.length || form.items.some((item) => !item.catalogItemId || Number(item.quantity) <= 0 || Number(item.unitPrice) <= 0)) next.items = "Selecione os produtos e informe quantidade e preço maiores que zero.";
    setErrors(next); return Object.keys(next).length === 0;
  }

  const saveMutation = useMutation({
    mutationFn: () => apiRequest<Quote>(editingId ? `/quotes/${editingId}` : "/quotes", { method: editingId ? "PUT" : "POST", body: JSON.stringify({ ...form, customerId: form.customerId || null, hasCommission: form.hasCommission === "true", idempotencyKey: editingId ? undefined : crypto.randomUUID() }) }),
    onSuccess: async (quote) => { setShowForm(false); setEditingId(null); setForm(blankForm()); setMessage(`${quote.number} salvo com sucesso.`); await Promise.all([client.invalidateQueries({ queryKey: ["quotes"] }), client.invalidateQueries({ queryKey: ["quote-options"] })]); }
  });
  const actionMutation = useMutation({
    mutationFn: ({ id, action }: { id: string; action: string }) => apiRequest(action === "convert" ? `/industrial/orders/from-quote/${id}` : `/quotes/${id}/${action}`, { method: "POST", body: "{}" }),
    onSuccess: async () => { setMessage("Situação atualizada com sucesso."); await client.invalidateQueries({ queryKey: ["quotes"] }); }
  });
  const productMutation = useMutation({
    mutationFn: () => apiRequest("/commercial/products", { method: "POST", body: JSON.stringify({ ...productForm, cureDuration: productForm.cureRequired ? Number(productForm.cureDuration) : null }) }),
    onSuccess: async () => { setShowProductForm(false); setProductForm({ code: "", name: "", description: "", category: "", unit: "UN", unitCost: "", suggestedPrice: "", cureRequired: true, cureDuration: "", cureTimeUnit: "DIAS", stockMinimum: "0", technicalNotes: "" }); await Promise.all([client.invalidateQueries({ queryKey: ["commercial-products"] }), client.invalidateQueries({ queryKey: ["quote-options"] })]); }
  });

  async function findCustomer() {
    if (form.customerPhone.replace(/\D/g, "").length < 10) return;
    try { const matches = await apiRequest<Options["customers"]>(`/quote-customers/search?phone=${encodeURIComponent(form.customerPhone)}`); if (matches.length === 1) { const customer = matches[0]; setForm((current) => ({ ...current, customerId: customer.id, customerName: customer.legalName, customerPhone: customer.phone ?? current.customerPhone, deliveryLocation: customer.deliveryAddresses[0]?.address ?? customer.addressLine ?? current.deliveryLocation })); setMessage("Cliente localizado pelo telefone."); } else if (matches.length > 1) setMessage("Há mais de um cliente com este telefone. Selecione o cliente na lista."); } catch (error) { setMessage((error as Error).message); }
  }

  function selectProduct(index: number, productId: string) { const product = options?.catalogItems.find((candidate) => candidate.id === productId); setForm((current) => ({ ...current, items: current.items.map((item, position) => position === index ? { ...item, catalogItemId: productId, unitPrice: product ? String(product.unitPrice) : "", code: product?.code, description: product?.name ?? product?.description, unit: product?.unit } : item) })); }
  async function editQuote(summary: Quote) { try { const quote = await apiRequest<Quote>(`/quotes/${summary.id}`); setEditingId(quote.id); setForm({ customerId: quote.customerId ?? "", customerName: quote.customerNameSnapshot ?? quote.customer?.legalName ?? "", customerPhone: quote.customerPhoneSnapshot ?? quote.customer?.phone ?? "", deliveryLocation: quote.deliveryLocation ?? "", paymentTermId: quote.paymentTermId ?? "", salespersonId: quote.salespersonId ?? "", hasCommission: quote.hasCommission === undefined ? "" : String(quote.hasCommission) as "true" | "false", salesSystem: quote.salesSystem ?? "", commercialNotes: quote.commercialNotes ?? "", items: quote.items?.map((item) => ({ catalogItemId: item.catalogItemId, quantity: String(item.quantity), unitPrice: String(item.unitPrice) })) ?? [blankItem()] }); setShowForm(true); } catch (error) { setMessage((error as Error).message); } }

  const mutationError = saveMutation.error ?? actionMutation.error ?? productMutation.error;
  return <div className="space-y-6">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-brand-700">Força de Vendas</p><h2 className="text-3xl font-extrabold">Orçamentos</h2><p className="mt-1 text-slate-600">Arcovan Artefatos de Concreto · orçamento, pedido, estoque e produção integrados.</p></div>{tab === "quotes" && can("QUOTE_CREATE") ? <button className="btn-primary" onClick={() => { setEditingId(null); setForm(blankForm()); setErrors({}); setShowForm(true); }}>Novo orçamento</button> : tab === "products" && can("PRODUCT_MANAGE") ? <button className="btn-primary" onClick={() => setShowProductForm(true)}>Novo produto</button> : null}</header>
    <nav className="flex gap-1 rounded-2xl border border-slate-200 bg-white p-1"><button className={tab === "quotes" ? "btn-primary" : "btn-secondary"} onClick={() => setTab("quotes")}>Orçamentos</button><button className={tab === "products" ? "btn-primary" : "btn-secondary"} onClick={() => setTab("products")}>Catálogo de produtos</button></nav>
    {message ? <p className="rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{message}</p> : null}{mutationError ? <p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-800">{(mutationError as Error).message}</p> : null}

    {tab === "quotes" ? <>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Orçamentos", quotesQuery.data?.summary.total], ["Em aberto", quotesQuery.data?.summary.open], ["Aprovados", quotesQuery.data?.summary.approved], ["Expirados", quotesQuery.data?.summary.expired], ["Valor orçado", brl(quotesQuery.data?.summary.quotedValue)]].map(([label, value]) => <div className="card" key={String(label)}><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-2 text-2xl font-extrabold">{value ?? "—"}</p></div>)}</section>
      <section className="card grid gap-3 md:grid-cols-3"><label className="text-xs font-bold">Número<input className="input mt-1" value={filters.number} onChange={(e) => setFilters({ ...filters, number: e.target.value, page: 1 })} /></label><label className="text-xs font-bold">Situação<select className="select mt-1" value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value, page: 1 })}><option value="">Todas</option>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></section>
      <section className="card overflow-hidden p-0"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>{["Número", "Emissão", "Cliente", "Vendedor", "Validade", "Valor", "Situação", "Ações"].map((label) => <th className="px-4 py-3" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{quotesQuery.isLoading ? <tr><td className="p-6 text-center" colSpan={8}>Carregando...</td></tr> : !quotesQuery.data?.items.length ? <tr><td className="p-6 text-center text-slate-500" colSpan={8}>Nenhum orçamento encontrado.</td></tr> : quotesQuery.data.items.map((quote) => <tr key={quote.id}><td className="px-4 py-3 font-extrabold">{quote.number}</td><td className="px-4 py-3">{brDate(quote.issueDate)}</td><td className="px-4 py-3">{quote.customerNameSnapshot ?? quote.customer?.legalName}</td><td className="px-4 py-3">{quote.salesperson?.name ?? "—"}</td><td className="px-4 py-3">{brDate(quote.validityDate)}</td><td className="px-4 py-3 font-bold">{brl(quote.total)}</td><td className="px-4 py-3"><span className="badge-neutral">{statusLabel[quote.status]}</span></td><td className="px-4 py-3"><div className="flex flex-wrap gap-1">{quote.status === "RASCUNHO" && can("QUOTE_EDIT") ? <button className="btn-secondary" onClick={() => void editQuote(quote)}>Editar</button> : null}{quote.status === "RASCUNHO" && can("QUOTE_ISSUE") ? <button className="btn-primary" onClick={() => actionMutation.mutate({ id: quote.id, action: "issue" })}>Emitir</button> : null}{quote.status === "EMITIDO" && can("QUOTE_ISSUE") ? <button className="btn-secondary" onClick={() => actionMutation.mutate({ id: quote.id, action: "send" })}>Marcar enviado</button> : null}{["EMITIDO", "ENVIADO"].includes(quote.status) && can("QUOTE_DECIDE") ? <button className="btn-primary" onClick={() => actionMutation.mutate({ id: quote.id, action: "approve" })}>Aprovar</button> : null}{quote.status === "APROVADO" && can("QUOTE_CONVERT") ? <button className="btn-primary" onClick={() => actionMutation.mutate({ id: quote.id, action: "convert" })}>Gerar pedido</button> : null}{quote.status !== "RASCUNHO" && can("QUOTE_DOCUMENT") ? <button className="btn-secondary" onClick={() => openPdf(quote.id)}>Imprimir/PDF</button> : null}</div></td></tr>)}</tbody></table></div></section>
    </> : <section className="card"><div className="mb-4 flex items-center justify-between gap-3"><h3 className="section-title">Catálogo de produtos</h3><input className="input max-w-sm" placeholder="Pesquisar por código ou nome" value={productSearch} onChange={(e) => setProductSearch(e.target.value)} /></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500">{["Código", "Produto", "Família", "Unidade", "Preço sugerido", "Custo interno", "Cura", "Situação"].map((label) => <th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody>{productsQuery.data?.filter((product) => `${product.code} ${product.name ?? product.description}`.toLowerCase().includes(productSearch.toLowerCase())).map((product) => <tr className="border-b" key={product.id}><td className="p-3 font-extrabold">{product.code}</td><td className="p-3">{product.name ?? product.description}</td><td className="p-3">{product.category ?? "—"}</td><td className="p-3">{product.unit}</td><td className="p-3">{brl(product.unitPrice)}</td><td className="p-3">{options?.permissions.viewCost ? brl(product.industrialConfig?.currentUnitCost) : "Restrito"}</td><td className="p-3">{product.industrialConfig?.cureRequired ? `${product.industrialConfig.cureDuration} ${product.industrialConfig.cureTimeUnit.toLowerCase()}` : "Não exige"}</td><td className="p-3">{product.isActive ? "Ativo" : "Inativo"}</td></tr>)}</tbody></table></div></section>}

    {showForm ? <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-4"><form className="mx-auto my-4 max-w-6xl rounded-[28px] bg-white p-6" onSubmit={(event) => { event.preventDefault(); if (validate()) saveMutation.mutate(); }}><div className="flex items-start justify-between"><div><h3 className="text-2xl font-extrabold">{editingId ? "Editar orçamento" : "Novo orçamento"}</h3><p className="text-sm text-slate-500">Empresa vinculada automaticamente: {options?.company.legalName ?? "Arcovan Artefatos de Concreto"}</p></div><button type="button" className="btn-secondary" onClick={() => setShowForm(false)}>Fechar</button></div>
      <div className="mt-6 grid gap-4 md:grid-cols-3"><Field label="Nome" error={errors.customerName}><input className="input mt-1" value={form.customerName} onChange={(e) => setForm({ ...form, customerName: e.target.value })} /></Field><Field label="Telefone" error={errors.customerPhone}><input className="input mt-1" placeholder="(00) 00000-0000" value={form.customerPhone} onBlur={findCustomer} onChange={(e) => setForm({ ...form, customerPhone: e.target.value, customerId: "" })} /></Field><Field label="Local de entrega" error={errors.deliveryLocation}><input className="input mt-1" value={form.deliveryLocation} onChange={(e) => setForm({ ...form, deliveryLocation: e.target.value })} /></Field><Field label="Data de emissão"><input className="input mt-1 bg-slate-50" readOnly value={brDate(options?.defaultDates.issueDate)} /></Field><Field label="Validade (15 dias corridos)"><input className="input mt-1 bg-slate-50" readOnly value={brDate(options?.defaultDates.validityDate)} /></Field><Field label="Condição de pagamento" error={errors.paymentTermId}><select className="select mt-1" value={form.paymentTermId} onChange={(e) => setForm({ ...form, paymentTermId: e.target.value })}><option value="">Selecione</option>{options?.paymentTerms.map((term) => <option key={term.id} value={term.id}>{term.name}</option>)}</select></Field><Field label="Responsável comercial" error={errors.salespersonId}><select className="select mt-1" value={form.salespersonId} onChange={(e) => setForm({ ...form, salespersonId: e.target.value })}><option value="">Selecione</option>{options?.salespersons.map((seller) => <option key={seller.id} value={seller.id}>{seller.code} — {seller.name}</option>)}</select></Field></div>
      <div className="mt-5 grid gap-4 rounded-2xl bg-slate-50 p-4 md:grid-cols-2"><Choice label="Este pedido possui comissão?" error={errors.hasCommission} name="commission" value={form.hasCommission} options={[["true", "Sim"], ["false", "Não"]]} onChange={(value) => setForm({ ...form, hasCommission: value as Form["hasCommission"] })} /><Choice label="Qual sistema deve ser utilizado para implantar o pedido?" error={errors.salesSystem} name="system" value={form.salesSystem} options={[["SHVENDAS", "SHVENDAS"], ["WEBMAIS", "WEBMAIS"]]} onChange={(value) => setForm({ ...form, salesSystem: value as Form["salesSystem"] })} /></div>
      <div className="mt-6 space-y-3"><div className="flex items-center justify-between"><h4 className="font-extrabold">Produtos</h4><button type="button" className="btn-secondary" onClick={() => setForm({ ...form, items: [...form.items, blankItem()] })}>Adicionar produto</button></div>{errors.items ? <p className="text-sm font-bold text-red-700">{errors.items}</p> : null}{form.items.map((item, index) => { const product = options?.catalogItems.find((candidate) => candidate.id === item.catalogItemId); return <div className="grid gap-3 rounded-2xl border border-slate-200 p-4 md:grid-cols-12" key={index}><label className="text-xs font-bold md:col-span-6">Produto<select className="select mt-1" value={item.catalogItemId} onChange={(e) => selectProduct(index, e.target.value)}><option value="">Pesquise por código ou nome</option>{options?.catalogItems.map((catalog) => <option key={catalog.id} value={catalog.id}>{catalog.code} — {catalog.name ?? catalog.description}</option>)}</select>{product ? <span className="mt-1 block text-slate-500">{product.unit} · preço sugerido {brl(product.unitPrice)}</span> : null}</label><label className="text-xs font-bold md:col-span-2">Quantidade<input className="input mt-1" type="number" min="0.0001" step="0.0001" value={item.quantity} onChange={(e) => setForm({ ...form, items: form.items.map((candidate, position) => position === index ? { ...candidate, quantity: e.target.value } : candidate) })} /></label><label className="text-xs font-bold md:col-span-2">Valor unitário<input className="input mt-1" type="number" min="0.01" step="0.0001" readOnly={!options?.permissions.editPrice} value={item.unitPrice} onChange={(e) => setForm({ ...form, items: form.items.map((candidate, position) => position === index ? { ...candidate, unitPrice: e.target.value } : candidate) })} /></label><div className="flex items-end md:col-span-2"><button type="button" className="btn-danger w-full" disabled={form.items.length === 1} onClick={() => setForm({ ...form, items: form.items.filter((_, position) => position !== index) })}>Remover</button></div></div>; })}</div>
      {options?.permissions.viewMargin ? <div className="mt-6 rounded-2xl border border-brand-200 bg-brand-50 p-4"><p className="text-xs font-bold uppercase text-brand-800">Prévia interna — o backend confirma os valores ao salvar</p><div className="mt-3 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Valor bruto", brl(preview.gross)], ["Custo", preview.missingCost ? "Custo ausente" : brl(preview.cost)], ["Comissão", brl(preview.commission)], ["Impostos", brl(preview.taxes)], ["Margem", brl(preview.margin)], ["Margem %", `${preview.percent.toFixed(2)}%`]].map(([label, value]) => <div key={label}><p className="text-xs text-slate-500">{label}</p><p className={`font-extrabold ${label === "Margem" && preview.margin < 0 ? "text-red-700" : ""}`}>{value}</p></div>)}</div></div> : null}
      <label className="mt-5 block text-xs font-bold">Informações comerciais internas<textarea className="input mt-1 min-h-20" value={form.commercialNotes} onChange={(e) => setForm({ ...form, commercialNotes: e.target.value })} /></label><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={() => setShowForm(false)}>Cancelar</button><button className="btn-primary" disabled={saveMutation.isPending}>{saveMutation.isPending ? "Salvando..." : "Salvar rascunho"}</button></div></form></div> : null}

    {showProductForm ? <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-4"><form className="mx-auto my-6 max-w-3xl rounded-[28px] bg-white p-6" onSubmit={(e) => { e.preventDefault(); productMutation.mutate(); }}><h3 className="text-2xl font-extrabold">Novo produto</h3><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Código"><input required className="input mt-1" value={productForm.code} onChange={(e) => setProductForm({ ...productForm, code: e.target.value })} /></Field><Field label="Nome"><input required className="input mt-1" value={productForm.name} onChange={(e) => setProductForm({ ...productForm, name: e.target.value })} /></Field><Field label="Família/categoria"><input className="input mt-1" value={productForm.category} onChange={(e) => setProductForm({ ...productForm, category: e.target.value })} /></Field><Field label="Unidade"><input required className="input mt-1" value={productForm.unit} onChange={(e) => setProductForm({ ...productForm, unit: e.target.value })} /></Field><Field label="Custo unitário interno"><input required type="number" min="0" step="0.0001" className="input mt-1" value={productForm.unitCost} onChange={(e) => setProductForm({ ...productForm, unitCost: e.target.value })} /></Field><Field label="Preço de venda sugerido"><input required type="number" min="0.01" step="0.0001" className="input mt-1" value={productForm.suggestedPrice} onChange={(e) => setProductForm({ ...productForm, suggestedPrice: e.target.value })} /></Field><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={productForm.cureRequired} onChange={(e) => setProductForm({ ...productForm, cureRequired: e.target.checked })} /> Produto exige cura</label>{productForm.cureRequired ? <div className="grid grid-cols-2 gap-2"><input required type="number" min="1" className="input" placeholder="Prazo" value={productForm.cureDuration} onChange={(e) => setProductForm({ ...productForm, cureDuration: e.target.value })} /><select className="select" value={productForm.cureTimeUnit} onChange={(e) => setProductForm({ ...productForm, cureTimeUnit: e.target.value as "HORAS" | "DIAS" })}><option value="HORAS">Horas</option><option value="DIAS">Dias</option></select></div> : null}</div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={() => setShowProductForm(false)}>Cancelar</button><button className="btn-primary" disabled={productMutation.isPending}>Cadastrar produto</button></div></form></div> : null}
  </div>;
}

function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="text-xs font-bold">{label}{children}{error ? <span className="mt-1 block text-red-700">{error}</span> : null}</label>; }
function Choice({ label, error, name, value, options, onChange }: { label: string; error?: string; name: string; value: string; options: string[][]; onChange: (value: string) => void }) { return <fieldset><legend className="text-sm font-extrabold">{label}</legend><div className="mt-2 flex gap-5">{options.map(([optionValue, optionLabel]) => <label className="flex items-center gap-2 text-sm" key={optionValue}><input type="radio" name={name} value={optionValue} checked={value === optionValue} onChange={() => onChange(optionValue)} />{optionLabel}</label>)}</div>{error ? <p className="mt-1 text-xs font-bold text-red-700">{error}</p> : null}</fieldset>; }
